version: '3.9'

services:
  nginx:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./.htpasswd:/etc/nginx/.htpasswd
      - ./main.html:/var/www/index.html
      - ./ping.html:/var/www/ping/index.html
    ports:
      - "8088:80"
